# Generated by Django 2.2.24 on 2022-06-19 12:22
import phonenumbers
from django.db import migrations


def validate_owners_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        parse_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(parse_number):
            pure_number = phonenumbers.format_number(
                parse_number,
                phonenumbers.PhoneNumberFormat.E164,
            )
            flat.owner_pure_phone = pure_number
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = ''
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_auto_20220619_0134'),
    ]

    operations = [
        migrations.RunPython(validate_owners_phonenumbers, move_backward),
    ]
