# Generated by Django 2.2.24 on 2022-06-21 21:32

from django.db import migrations


def copy_flat_data_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all().iterator():
        owner_obj, created = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )
        owner_obj.flat.add(flat)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0010_auto_20220622_0031'),
    ]

    operations = [
        migrations.RunPython(copy_flat_data_to_owner, move_backward)
    ]
